"""
pdf_exporter.py — Glow.ai v2
Converts markdown research output into a styled, downloadable PDF.
Uses WeasyPrint (preferred) with a fallback to reportlab.
"""

import io
import re


# ── Markdown → HTML ────────────────────────────────────────────────────────────
def markdown_to_html(markdown: str, title: str = "Glow.ai Research") -> str:
    """Convert markdown to a full styled HTML document for PDF rendering."""

    body = markdown
    body = re.sub(r'^# (.+)$',   r'<h1>\1</h1>',   body, flags=re.MULTILINE)
    body = re.sub(r'^## (.+)$',  r'<h2>\1</h2>',   body, flags=re.MULTILINE)
    body = re.sub(r'^### (.+)$', r'<h3>\1</h3>',   body, flags=re.MULTILINE)
    body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', body)
    body = re.sub(r'\*(.+?)\*',     r'<em>\1</em>',          body)
    body = re.sub(r'`(.+?)`',       r'<code>\1</code>',      body)
    body = re.sub(r'^> (.+)$',  r'<blockquote>\1</blockquote>', body, flags=re.MULTILINE)
    body = re.sub(r'^---$',     r'<hr/>',                        body, flags=re.MULTILINE)

    # Lists
    body = re.sub(r'^[-*] (.+)$',    r'<li>\1</li>', body, flags=re.MULTILINE)
    body = re.sub(r'^\d+\. (.+)$',   r'<li>\1</li>', body, flags=re.MULTILINE)
    body = re.sub(r'(<li>.*?</li>\n?)+', lambda m: f'<ul>{m.group()}</ul>', body, flags=re.DOTALL)

    # Paragraphs
    lines = body.split('\n')
    result = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            result.append('')
        elif re.match(r'^<(h[1-3]|ul|ol|li|blockquote|hr|p)', stripped):
            result.append(stripped)
        else:
            result.append(f'<p>{stripped}</p>')
    body = '\n'.join(result)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>{title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,700;1,400&display=swap');
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Inter', Georgia, serif;
    font-size: 11pt;
    line-height: 1.75;
    color: #1a1a1a;
    padding: 60px 72px;
    max-width: 800px;
    margin: 0 auto;
  }}
  .header {{
    border-bottom: 2px solid #1a3a2a;
    padding-bottom: 20px;
    margin-bottom: 36px;
  }}
  .brand {{
    font-family: 'Playfair Display', Georgia, serif;
    font-size: 20pt;
    font-weight: 700;
    color: #1a3a2a;
    letter-spacing: -0.02em;
  }}
  .brand span {{ color: #10b981; font-style: italic; }}
  .meta {{ font-size: 9pt; color: #888; margin-top: 4px; }}
  h1 {{
    font-family: 'Playfair Display', Georgia, serif;
    font-size: 20pt;
    font-weight: 700;
    color: #111;
    margin: 28px 0 10px;
    line-height: 1.25;
  }}
  h2 {{
    font-family: 'Inter', sans-serif;
    font-size: 13pt;
    font-weight: 600;
    color: #1a3a2a;
    margin: 24px 0 8px;
    padding-bottom: 5px;
    border-bottom: 1px solid #e0ede8;
  }}
  h3 {{
    font-family: 'Inter', sans-serif;
    font-size: 11pt;
    font-weight: 500;
    color: #333;
    margin: 18px 0 6px;
  }}
  p  {{ margin: 8px 0; color: #333; }}
  ul {{ padding-left: 20px; margin: 8px 0; }}
  li {{ margin: 4px 0; color: #333; }}
  strong {{ font-weight: 600; color: #111; }}
  em {{ font-style: italic; color: #555; }}
  code {{
    font-family: 'Courier New', monospace;
    font-size: 9pt;
    background: #f3f3f3;
    padding: 1px 5px;
    border-radius: 3px;
    color: #1a3a2a;
  }}
  blockquote {{
    border-left: 3px solid #10b981;
    padding: 8px 16px;
    margin: 12px 0;
    color: #555;
    background: #f8fdf9;
    border-radius: 0 4px 4px 0;
  }}
  hr {{ border: none; border-top: 1px solid #e5e5e5; margin: 20px 0; }}
  .footer {{
    margin-top: 48px;
    padding-top: 16px;
    border-top: 1px solid #e5e5e5;
    font-size: 8pt;
    color: #aaa;
    text-align: center;
  }}
</style>
</head>
<body>
  <div class="header">
    <div class="brand">Glow<span>.ai</span></div>
    <div class="meta">Research output — generated by Glow.ai Academic Research Agent</div>
  </div>
  {body}
  <div class="footer">Generated by Glow.ai · Academic Research Agent · For educational use</div>
</body>
</html>"""


# ── PDF generation ─────────────────────────────────────────────────────────────
def generate_pdf(markdown: str, title: str = "Glow Research") -> bytes:
    """
    Convert markdown to PDF bytes.
    Tries WeasyPrint first, falls back to basic reportlab.
    """
    html = markdown_to_html(markdown, title)

    # ── WeasyPrint ─────────────────────────────────────────────────────────────
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except ImportError:
        pass
    except Exception as e:
        print(f"WeasyPrint error: {e}")

    # ── Fallback: reportlab (plain text PDF) ───────────────────────────────────
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.enums import TA_LEFT

        buf    = io.BytesIO()
        doc    = SimpleDocTemplate(buf, pagesize=A4,
                                   leftMargin=2.5*cm, rightMargin=2.5*cm,
                                   topMargin=2.5*cm, bottomMargin=2.5*cm)
        styles = getSampleStyleSheet()

        h1_style = ParagraphStyle('H1', parent=styles['Heading1'],
                                  fontSize=18, textColor=colors.HexColor('#1a3a2a'), spaceAfter=10)
        h2_style = ParagraphStyle('H2', parent=styles['Heading2'],
                                  fontSize=13, textColor=colors.HexColor('#1a3a2a'), spaceAfter=6)
        h3_style = ParagraphStyle('H3', parent=styles['Heading3'],
                                  fontSize=11, textColor=colors.HexColor('#333333'), spaceAfter=4)
        body_style = ParagraphStyle('Body', parent=styles['Normal'],
                                    fontSize=10, leading=16, textColor=colors.HexColor('#333333'))

        story = [
            Paragraph("Glow.ai — Research Output", h1_style),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor('#10b981')),
            Spacer(1, 12),
        ]

        for line in markdown.split('\n'):
            s = line.strip()
            if not s:
                story.append(Spacer(1, 6))
            elif s.startswith('# '):
                story.append(Paragraph(s[2:], h1_style))
            elif s.startswith('## '):
                story.append(Paragraph(s[3:], h2_style))
            elif s.startswith('### '):
                story.append(Paragraph(s[4:], h3_style))
            elif s.startswith(('- ', '* ')):
                story.append(Paragraph(f"• {s[2:]}", body_style))
            elif s == '---':
                story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
            else:
                clean = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', s)
                clean = re.sub(r'\*(.+?)\*', r'<i>\1</i>', clean)
                story.append(Paragraph(clean, body_style))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        raise RuntimeError("No PDF library available. Install WeasyPrint or ReportLab.")
